name: CI/CD Pipeline for API

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "api/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "api/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build
